config/routes.rb
Rails.application.routes.draw do
  get 'weight_records/new'
  post 'weight_records/create'
  get 'weight_records/index'
  get 'weight_records/show/:id', to:'weight_records#show', as: 'weight_records_show'
  get 'weight_records/show'
  get 'weight_records/edit/:id', to:'weight_records#edit', as: 'weight_records_edit'
  patch 'weight_records/update/:id', to:'weight_records#update', as: 'weight_records_update'
  delete 'weight_records/destroy/:id', to:'weight_records#destroy', as: 'weight_records_destroy'
  get 'members/new'
  post 'members/create'
  get 'members/index'
  get 'members/show/:id', to:'members#show', as: 'members_show'
  get 'members/show/name/:name', to:'members#show', as: 'members_name_show'
  get 'members/edit/:id', to:'members#edit', as: 'members_edit'
  patch 'members/update/:id', to:'members#update', as: 'members_update'
  delete 'members/destroy/:id', to: 'members#destroy', as: 'members_destroy'
  root 'static_pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :weight_records, -> { order(created_at: :asc)}, dependent: :destroy

  validates :name, presence: true
  #validates :height, presence: true
  
  def self.member_select
    hash = {}
    Member.all.each do |mem|
      hash[mem.name] = mem.id
    end
    hash
  end

end

app/models/weight_record.rb
class WeightRecord < ApplicationRecord
  belongs_to :member

  validates :member_id, presence: true
  validates :date, presence: true, uniqueness: { scope: :member_id, message: "指定の日付の記録は存在します。" }
  validates :weight, presence: true
  
  def self.member_week(mem_id)
    weight_record_array = []
    ((Date.today - 6)..Date.today).each do |d|
      weight_record_array << self.where(date: d, member_id: mem_id)
    end
    weight_record_array
  end

  def start_time
    self.date.to_time.to_datetime
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:success] = "作成しました"
      #redirect_to members_show_path(@member.id)
      redirect_to members_index_path
    else
      flash.now[:danger] = "失敗しました"
      render 'new', status: :unprocessable_entity and return
    end
  end

  def index
    @members = Member.all
  end

  def show
    if params[:id].present?
      @member = Member.find(params[:id])
    elsif params[:name].present?
      @member = Member.find_by(name:params[:name])
    end
    if @member.blank? && params[:name].present?
      redirect_to members_new_path
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:success] = "編集しました"
      redirect_to "#{members_show_path}"
    else
      flash.now[:danger] = "失敗しました"
      render edit, status: :unprocessable_entity and return
    end
  end

  def destroy
    Member.find(params[:id]).destroy
    flash[:success] = "消した"
    redirect_to members_index_path
  end


  private


  def member_params
    params.require(:member).permit(:name, :height)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/weight_records_controller.rb
class WeightRecordsController < ApplicationController
  def new
    if Member.all.count <= 0
      redirect_to members_new_path
    elsif params[:date].nil?
      @weight_record = WeightRecord.new(date: Date.today)
    else
      @weight_record = WeightRecord.new(member_id:params[:member_id], date:params[:date])
    end
  end

  def create
    @weight_record = WeightRecord.new(weight_record_params)
    if @weight_record.save
      flash[:success] = "登録完了"
      redirect_to weight_records_index_path
    else
      flash.now[:danger] = "登録失敗"
      render 'new', status: :unprocessable_entity and return
    end
  end

  def index
    @weight_records = WeightRecord.all
  end

  def show
    @weight_record = WeightRecord.find(params[:id])
  end

  def edit
    @weight_record = WeightRecord.find(params[:id])
  end

  def update
    @weight_record = WeightRecord.find(params[:id])
    if @weight_record.update(weight_record_params)
      flash[:success] = "編集完了"
      redirect_to "#{weight_records_show_path}"
    else
      flash.now[:danger] = "編集失敗"
      render 'show', status: :unprocessable_entity and return
    end
  end

  def destroy
    if WeightRecord.find(params[:id]).destroy
      flash[:success] = "消しました"
      redirect_to weight_records_index_path
    else
      flash.now[:danger] = "削除失敗"
      render 'show', status: :unprocessable_entity and return
    end
  end

  private

  def weight_record_params
    params.require(:weight_record).permit(:member_id, :date, :weight, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = '体重記録'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/weight_records_helper.rb
module WeightRecordsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%# javascript_importmap_tags %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item"><%= link_to "ホーム", root_url, class: "nav-link active navbar-brand" %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">メンバー</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "新規メンバー登録", members_new_path, class:"dropdown-item" %></li>
              <li><%= link_to "メンバー一覧", members_index_path, class:"dropdown-item" %></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">体重</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to "体重登録", weight_records_new_path, class:"dropdown-item" %></li>
              <li><%= link_to "最近の体重", weight_records_index_path, class:"dropdown-item" %></li>
            </ul>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_tmp.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav nav-fill w-100 align-items-start">
        <li class="nav-item"><%= link_to "ホーム", root_url %></li><!--
        <li class="nav-item"><%= link_to "車番データ(未実装)", cars_new_path %></li>-->
        <li class="nav-item"><%= link_to "掲示板(未実装)", '#' %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">車番データ(未実装)</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to "新規作成", cars_new_path, class:"dropdown-item" %></li>
            <li><%= link_to "一覧", cars_index_path, class:"dropdown-item" %></li>
            <li><%= link_to "検索", cars_search_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |msg_type,msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%# render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, url: path, data: form_data, autocomplete: "off") do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<p class="form-group">
  <%= f.label :名前, class: "form-label" %>
  <%= f.text_field :name, class: "form-control", autocomplete: "off" %>
</p>

<p class="form-group">
  <%= f.label "身長(cm)", class: "form-label" %>
  <%= f.number_field :height, step:"0.1", class: "form-control", autocomplete: "off" %>
</p>

<p>
  <%= f.submit submit_text, class: "btn btn-primary btn-lg container-fluid" %>
</p>

<% end %>

app/views/members/_show_calendar.html.erb
<%= month_calendar events: mem_records do |d, records| %>
  <%= d.day %>

  <% records.each do |wr| %>
    <div>
      <%= link_to "#{wr.weight}", weight_records_show_path(wr.id) %>
    </div>
  <% end %>
  <% if records.count == 0 %>
    <div>
      <%= link_to "未", weight_records_new_path(member_id:mem.id, date:d)%>
    </div>
  <% end %>
<% end %>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/destroy.html.erb
<h1>Members#destroy</h1>
<p>Find me in app/views/members/destroy.html.erb</p>

app/views/members/edit.html.erb
<h1><%= @member.name %></h1>
<%= render 'members/form', member:@member, path: members_update_path, submit_text: "メンバー編集", form_data: { turbo: false } %>

app/views/members/index.html.erb
<h1>メンバー一覧</h1>
<div class="d-grid gap-2">
<% @members.each do |mem| %>
  <p>
    <%= link_to "#{mem.name}", members_show_path(mem.id), class: "btn btn-info container-fluid" %>
  </p>
<% end %>

app/views/members/new.html.erb
<% provide(:title, 'メンバー登録') %>
<h1>メンバー新規登録</h1>
<%= render 'members/form', member:@member, path: members_create_path, submit_text: "新規メンバー作成", form_data: { turbo: false } %>

app/views/members/show.html.erb
<h1><%= @member.name  %></h1>
<% if @member.height.present? %>
  <p><%= @member.height %> cm</p>
<% else %>
  <p><%= link_to '身長未登録', members_edit_path(@member.id) %></p>  
<% end %>
<%= render 'members/show_calendar', mem_records: @member.weight_records, mem: @member %>

<div class="row">
  <%= link_to '編集', members_edit_path(@member.id), class:"col btn btn-lg btn-primary" %>
  <%= link_to '削除', members_destroy_path(@member.id), data: { turbo_method: :delete, turbo_confirm: "消すの？" }, class:"col btn btn-lg btn-danger" %>
</div>

app/views/members/update.html.erb
<h1>Members#update</h1>
<p>Find me in app/views/members/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>体重記録</h1>
<div class="d-grid gap-2">
  <% Member.all.each do |mem| %>
    <p><%= link_to "#{mem.name}", weight_records_new_path(member_id: mem.id, date: Date.today), class: "btn btn-lg btn-info container-fluid" %></p>
  <% end %>
  <%# if Member.all.count == 0 %>
    <p><%= link_to '新規メンバー登録', members_new_path, class: "btn btn-primary btn-lg container-fluid" %></p>
  <%# end %>

</div>

app/views/weight_records/_edit_form.html.erb
<%= form_with(model: weight_record, url: path, data: form_data, autocomplete: "off") do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<% weight_record.member_id.blank? ? sel_params = Member.first.id : sel_params = weight_record.member_id %>
<p class="form-group">
  <%= f.label :登録者, class: "form-label" %><br>
  <%= f.select :member_id, options_for_select(Member.member_select, sel_params), class: "form-select form-control" %>
</p>

<p class="form-group">
  <%= f.label :日付, class: "form-label" %><br>
  <%# f.date_field :date, value: Date.today %>
  <%= f.date_field :date %>
</p>

<p class="form-group">
  <%= f.label :体重, class: "form-label" %>
  <%= f.number_field :weight, step:0.1, class:"form-control", autocomplete:"off" %>
</p>

<p>
  <%= f.label :コメント%>
  <%= %>
</p>

<p>
  <%= f.submit submit_text, class: "btn btn-primary btn-lg container-fluid" %>
</p>

<% end %>

app/views/weight_records/_form.html.erb
<%= form_with(model: weight_record, url: path, data: form_data, autocomplete: "off") do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<% weight_record.member_id.blank? ? sel_params = Member.first.id : sel_params = weight_record.member_id %>
<p class="form-group">
  <%= f.label :登録者, class: "form-label" %><br>
  <% if is_edit %>
    <%= f.select :member_id, options_for_select({ weight_record.member.name => weight_record.member_id }, sel_params), class: "form-select form-control" %>
  <% else %>
    <%= f.select :member_id, options_for_select(Member.member_select, sel_params), class: "form-select form-control" %>
  <% end %>
</p>

<p class="form-group">
  <%= f.label :日付, class: "form-label" %><br>
  <%# f.date_field :date, value: Date.today %>
  <%= f.date_field :date, readonly: is_edit %>
</p>

<p class="form-group">
  <%= f.label :体重, class: "form-label" %>
  <%= f.number_field :weight, step:0.1, class:"form-control", autocomplete:"off" %>
</p>

<p>
  <%= f.label :コメント %>
  <%= f.text_field :comment, class: "form-control" %>
</p>

<p>
  <%= f.submit submit_text, class: "btn btn-primary btn-lg container-fluid" %>
</p>

<% end %>

app/views/weight_records/_index_table.html.erb
<div class="table-responsive text-nowrap">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="table-fixed"></th>
        <% ((Date.today - 6)..Date.today).each do |d| %>
          <th scope="col"><%= d.strftime("%m/%d") %></th>
        <% end %>
      </tr>
    </thread>
    <tbody>
      <% Member.all.each do |mem| %>
        <tr class="table-column">
          <th scope="row" class="table-fixed"><%= link_to mem.name, members_show_path(mem.id), class: "btn btn-primary" %></th>
          <% WeightRecord.member_week(mem.id).each_with_index do |wr, i| %>
            <% if wr.blank? %>
              <td scope="row" class="table-no-data"><%= link_to "未登録", weight_records_new_path(member_id:mem.id, date:(Date.today - 6 + i) ) %></td>
            <% else %>
              <!-- <td scope="row"><%= wr.to_a[0].weight %>kg</td> -->
              <td scope="row"><%= link_to "#{wr.to_a[0].weight}kg", weight_records_show_path(wr.to_a[0].id) %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/weight_records/create.html.erb
<h1>WeightRecords#create</h1>
<p>Find me in app/views/weight_records/create.html.erb</p>

app/views/weight_records/destroy.html.erb
<h1>WeightRecords#destroy</h1>
<p>Find me in app/views/weight_records/destroy.html.erb</p>

app/views/weight_records/edit.html.erb
<h1>編集　<%= @weight_record.member.name + ' ' + @weight_record.date.strftime("%m/%d") %></h1>
<%= render 'weight_records/form', weight_record: @weight_record, path: weight_records_update_path, submit_text: '体重編集', is_edit: true, form_data: { turbo: false } %>

app/views/weight_records/index.html.erb
<h1>最近の記録</h1>

<!--
<% Member.all.each do |mem| %>
  <%= link_to "#{mem.name}", members_show_path(mem.id) %><br>
  <% mem.weight_records.order(date: :desc).limit(7).each do |wr| %>
    <%= wr.date %>@<%= wr.weight %>kg<br>
  <% end %>
<% end %>
-->

<%= render 'weight_records/index_table' %>

app/views/weight_records/new.html.erb
<% provide(:title, '体重登録') %>
<h1>体重登録</h1>
<%= render 'weight_records/form', weight_record:@weight_record, path: weight_records_create_path, submit_text: "体重登録", is_edit: false, form_data: { turbo: false } %>

app/views/weight_records/show.html.erb
<h1><%= @weight_record.member.name + ' ' + @weight_record.date.strftime("%m/%d") %></h1>
<p>体重<br><%= @weight_record.weight %>kg</p>
<p>コメント<br><%= @weight_record.comment %></p>
<div class="row">
  <%= link_to '編集', weight_records_edit_path(@weight_record.id), class:"col btn btn-lg btn-primary" %>
  <%= link_to '削除', weight_records_destroy_path(@weight_record.id), data: { turbo_method: :delete, turbo_confirm: "消すの？" }, class:"col btn btn-lg btn-danger" %>
</div>

app/views/weight_records/update.html.erb
<h1>WeightRecords#update</h1>
<p>Find me in app/views/weight_records/update.html.erb</p>